// Descrições completas das 443 variáveis GEP (Moagem 2 tem 105, não 106)

const VARIABLE_DESCRIPTIONS: Record<string, { name: string; unit: string; description: string; isRunningIndicator?: boolean }> = {
  // MOAGEM 1 (Z01) - 106 variáveis
  'Z01_VAR_001': { name: 'Status Moinho', unit: '', description: 'Sinaliza funcionamento motor principal do moinho (1=Ligado, 0=Desligado)', isRunningIndicator: true },
  'Z01_VAR_002': { name: 'Produto Selecionado', unit: '', description: 'Seleção de produto produzido (1=CPIII 40 RS, 2=CPII E40, 3=Ensacado)' },
  'Z01_VAR_003': { name: 'Vazão Calcário %', unit: '%', description: 'Porcentagem de vazão da balança de calcário' },
  'Z01_VAR_004': { name: 'Vazão Calcário Desejada', unit: 't/h', description: 'Vazão desejada da balança de calcário' },
  'Z01_VAR_005': { name: 'Umidade Calcário', unit: '%', description: 'Umidade do material da balança de calcário' },
  'Z01_VAR_006': { name: 'Vazão Calcário Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de calcário' },
  'Z01_VAR_007': { name: 'Vazão Calcário Seca', unit: 't/h', description: 'Vazão do material base seca na balança de calcário' },
  'Z01_VAR_008': { name: 'Total Calcário Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de calcário' },
  'Z01_VAR_009': { name: 'Total Calcário Seco', unit: 't', description: 'Totalizador do material base seca na balança de calcário' },
  'Z01_VAR_010': { name: 'Vazão Gesso %', unit: '%', description: 'Porcentagem de vazão da balança de gesso' },
  'Z01_VAR_011': { name: 'Vazão Gesso Desejada', unit: 't/h', description: 'Vazão desejada da balança de gesso' },
  'Z01_VAR_012': { name: 'Umidade Gesso', unit: '%', description: 'Umidade do material da balança de gesso' },
  'Z01_VAR_013': { name: 'Vazão Gesso Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de gesso' },
  'Z01_VAR_014': { name: 'Vazão Gesso Seca', unit: 't/h', description: 'Vazão do material base seca na balança de gesso' },
  'Z01_VAR_015': { name: 'Total Gesso Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de gesso' },
  'Z01_VAR_016': { name: 'Total Gesso Seco', unit: 't', description: 'Totalizador do material base seca na balança de gesso' },
  'Z01_VAR_017': { name: 'Vazão Escória %', unit: '%', description: 'Porcentagem de vazão da balança de escória' },
  'Z01_VAR_018': { name: 'Vazão Escória Desejada', unit: 't/h', description: 'Vazão desejada da balança de escória' },
  'Z01_VAR_019': { name: 'Umidade Escória', unit: '%', description: 'Umidade do material da balança de escória' },
  'Z01_VAR_020': { name: 'Vazão Escória Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de escória' },
  'Z01_VAR_021': { name: 'Vazão Escória Seca', unit: 't/h', description: 'Vazão do material base seca na balança de escória' },
  'Z01_VAR_022': { name: 'Total Escória Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de escória' },
  'Z01_VAR_023': { name: 'Total Clínquer Seco', unit: 't', description: 'Totalizador do material base seca na balança de clínquer' },
  'Z01_VAR_024': { name: 'Vazão Clínquer %', unit: '%', description: 'Porcentagem de vazão da balança de clínquer' },
  'Z01_VAR_025': { name: 'Vazão Clínquer Desejada', unit: 't/h', description: 'Vazão desejada da balança de clínquer' },
  'Z01_VAR_026': { name: 'Umidade Clínquer', unit: '%', description: 'Umidade do material da balança de clínquer' },
  'Z01_VAR_027': { name: 'Vazão Clínquer Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de clínquer' },
  'Z01_VAR_028': { name: 'Vazão Clínquer Seca', unit: 't/h', description: 'Vazão do material base seca na balança de clínquer' },
  'Z01_VAR_029': { name: 'Total Clínquer Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de clínquer' },
  'Z01_VAR_030': { name: 'Total Escória Seco', unit: 't', description: 'Totalizador do material base seca na balança de escória' },
  'Z01_VAR_031': { name: 'Soma Total %', unit: '%', description: 'Soma total porcentagem das balanças dosadoras' },
  'Z01_VAR_032': { name: 'Soma Vazão Úmida', unit: 't/h', description: 'Soma total vazão úmida das balanças dosadoras' },
  'Z01_VAR_033': { name: 'Soma Vazão Seca', unit: 't/h', description: 'Soma total vazão seca das balanças dosadoras' },
  'Z01_VAR_034': { name: 'SP Corrente Elevador', unit: 'A', description: 'Set-point corrente elevador retorno de controle do PID' },
  'Z01_VAR_035': { name: 'SP Produção PID', unit: 't/h', description: 'Set-point de produção do moinho' },
  'Z01_VAR_036': { name: 'SP Produção Manual', unit: 't/h', description: 'Set-point manual da produção do moinho' },
  'Z01_VAR_037': { name: 'Limite Máx Produção', unit: 't/h', description: 'Limite máximo de produção do moinho' },
  'Z01_VAR_038': { name: 'Vazão Total Úmida', unit: 't/h', description: 'Soma total vazão úmida das balanças dosadoras' },
  'Z01_VAR_039': { name: 'Total Consumo', unit: 't', description: 'Soma do totalizador consumo moagem 1' },
  'Z01_VAR_040': { name: 'Total Inicial Balanças', unit: 't', description: 'Totalizador inicial das balanças moagem 1' },
  'Z01_VAR_041': { name: 'Total Inicial Consumo', unit: 't', description: 'Totalizador inicial consumo moagem 1' },
  'Z01_VAR_042': { name: 'Horas Funcionamento', unit: 'h', description: 'Totalizador funcionamento (horas) do motor principal do moinho' },
  'Z01_VAR_043': { name: 'Minutos Funcionamento', unit: 'min', description: 'Totalizador funcionamento (minutos) do motor principal do moinho' },
  'Z01_VAR_044': { name: 'Segundos Funcionamento', unit: 's', description: 'Totalizador funcionamento (segundos) do motor principal do moinho' },
  'Z01_VAR_045': { name: 'Temperatura Saída', unit: '°C', description: 'Leitura temperatura de saída do moinho' },
  'Z01_VAR_046': { name: 'Pressão Entrada Moinho', unit: 'mbar', description: 'Leitura pressão entrada do moinho 1' },
  'Z01_VAR_047': { name: 'Pressão Entrada Filtro', unit: 'mbar', description: 'Leitura pressão entrada do filtro de processo' },
  'Z01_VAR_048': { name: 'Pressão Saída Filtro', unit: 'mbar', description: 'Leitura pressão saída do filtro de processo' },
  'Z01_VAR_049': { name: 'Temp Entrada Filtro', unit: '°C', description: 'Leitura temperatura entrada filtro de processo' },
  'Z01_VAR_050': { name: 'Temp Saída p/ Separador', unit: '°C', description: 'Leitura temperatura da saída do moinho para o separador' },
  'Z01_VAR_051': { name: 'Pressão Saída p/ Separador', unit: 'mbar', description: 'Leitura pressão da saída do moinho para o separador' },
  'Z01_VAR_052': { name: 'Abertura Válvula Ar', unit: '%', description: 'Leitura abertura válvula ar primário do separador' },
  'Z01_VAR_053': { name: 'Pressão Diferencial Filtro', unit: 'mbar', description: 'Leitura pressão diferencial do filtro de processo' },
  'Z01_VAR_054': { name: 'Consumo Energia Motor', unit: 'kWh', description: 'Totalizador de Consumo de Energia do Motor do moinho' },
  'Z01_VAR_055': { name: 'Consumo Energia CCM1', unit: 'kWh', description: 'Totalizador de Consumo de Energia do CCM 1' },
  'Z01_VAR_056': { name: 'Tensão L1-N CCM1', unit: 'V', description: 'Leitura tensão entre L1 e neutro do CCM 1' },
  'Z01_VAR_057': { name: 'Tensão L2-N CCM1', unit: 'V', description: 'Leitura tensão entre L2 e neutro do CCM 1' },
  'Z01_VAR_058': { name: 'Tensão L3-N CCM1', unit: 'V', description: 'Leitura tensão entre L3 e neutro do CCM 1' },
  'Z01_VAR_059': { name: 'Tensão L1-L2 CCM1', unit: 'V', description: 'Leitura tensão entre L1 e L2 do CCM 1' },
  'Z01_VAR_060': { name: 'Tensão L2-L3 CCM1', unit: 'V', description: 'Leitura tensão entre L2 e L3 do CCM 1' },
  'Z01_VAR_061': { name: 'Tensão L1-L3 CCM1', unit: 'V', description: 'Leitura tensão entre L1 e L3 do CCM 1' },
  'Z01_VAR_062': { name: 'Corrente L1 CCM1', unit: 'A', description: 'Leitura corrente em L1 do CCM 1' },
  'Z01_VAR_063': { name: 'Corrente L2 CCM1', unit: 'A', description: 'Leitura corrente em L2 do CCM 1' },
  'Z01_VAR_064': { name: 'Corrente L3 CCM1', unit: 'A', description: 'Leitura corrente em L3 do CCM 1' },
  'Z01_VAR_065': { name: 'Potência Ativa CCM1', unit: 'kW', description: 'Leitura potência ativa total do CCM 1' },
  'Z01_VAR_066': { name: 'Potência Reativa CCM1', unit: 'kVAr', description: 'Leitura potência reativa total do CCM 1' },
  'Z01_VAR_067': { name: 'Demanda Potência CCM1', unit: 'kW', description: 'Leitura demanda potência ativa do CCM 1' },
  'Z01_VAR_068': { name: 'Fator Potência CCM1', unit: '', description: 'Leitura fator de potência total do CCM 1' },
  'Z01_VAR_069': { name: 'Energia Consumida CCM1', unit: 'kWh', description: 'Leitura Energia consumida do CCM 1' },
  'Z01_VAR_070': { name: 'Silo Selecionado', unit: '', description: 'Seleção de produção do moinho (1=Silo 1, 2=Silo 2, 3=Silo 3, 4=Silo 4)' },
  'Z01_VAR_071': { name: 'Tensão L1-N Motor', unit: 'V', description: 'Leitura tensão entre L1 e neutro do Motor principal do moinho' },
  'Z01_VAR_072': { name: 'Tensão L2-N Motor', unit: 'V', description: 'Leitura tensão entre L2 e neutro do Motor principal do moinho' },
  'Z01_VAR_073': { name: 'Tensão L3-N Motor', unit: 'V', description: 'Leitura tensão entre L3 e neutro do Motor principal do moinho' },
  'Z01_VAR_074': { name: 'Tensão L1-L2 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L2 do Motor principal do moinho' },
  'Z01_VAR_075': { name: 'Tensão L2-L3 Motor', unit: 'V', description: 'Leitura tensão entre L2 e L3 do Motor principal do moinho' },
  'Z01_VAR_076': { name: 'Tensão L1-L3 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L3 do Motor principal do moinho' },
  'Z01_VAR_077': { name: 'Corrente L1 Motor', unit: 'A', description: 'Leitura corrente em L1 do Motor principal do moinho' },
  'Z01_VAR_078': { name: 'Corrente L2 Motor', unit: 'A', description: 'Leitura corrente em L2 do Motor principal do moinho' },
  'Z01_VAR_079': { name: 'Corrente L3 Motor', unit: 'A', description: 'Leitura corrente em L3 do Motor principal do moinho' },
  'Z01_VAR_080': { name: 'Potência Ativa Motor', unit: 'kW', description: 'Leitura potência ativa total do Motor principal do moinho' },
  'Z01_VAR_081': { name: 'Potência Reativa Motor', unit: 'kVAr', description: 'Leitura potência reativa total do Motor principal do moinho' },
  'Z01_VAR_082': { name: 'Demanda Potência Motor', unit: 'kW', description: 'Leitura demanda potência ativa do Motor principal do moinho' },
  'Z01_VAR_083': { name: 'Fator Potência Motor', unit: '', description: 'Leitura fator de potência total do Motor principal do moinho' },
  'Z01_VAR_084': { name: 'Energia Consumida Motor', unit: 'kWh', description: 'Leitura Energia consumida do Motor principal do moinho' },
  'Z01_VAR_085': { name: 'Corrente % Motor', unit: '%', description: 'Leitura corrente em Porcentagem Motor principal moinho' },
  'Z01_VAR_086': { name: 'Corrente % Elevador Proc', unit: '%', description: 'Leitura corrente em Porcentagem elevador de processo' },
  'Z01_VAR_087': { name: 'Corrente Elevador Proc', unit: 'A', description: 'Leitura corrente em amperes elevador de processo' },
  'Z01_VAR_088': { name: 'SP Velocidade Elevador', unit: 'Hz', description: 'Set-point velocidade elevador de processo' },
  'Z01_VAR_089': { name: 'Frequência Elevador', unit: 'Hz', description: 'Indicação velocidade em frequência elevador de processo' },
  'Z01_VAR_090': { name: 'RPM Elevador Processo', unit: 'RPM', description: 'Indicação velocidade em RPM elevador de processo' },
  'Z01_VAR_091': { name: 'Corrente % Vent Filtro', unit: '%', description: 'Leitura corrente em Porcentagem ventilador filtro de processo' },
  'Z01_VAR_092': { name: 'Corrente Vent Filtro', unit: 'A', description: 'Leitura corrente em amperes ventilador filtro de processo' },
  'Z01_VAR_093': { name: 'SP Velocidade Vent Filtro', unit: 'Hz', description: 'Set-point velocidade ventilador filtro de processo' },
  'Z01_VAR_094': { name: 'Frequência Vent Filtro', unit: 'Hz', description: 'Indicação velocidade em frequência ventilador filtro de processo' },
  'Z01_VAR_095': { name: 'RPM Vent Filtro', unit: 'RPM', description: 'Indicação velocidade em RPM ventilador filtro de processo' },
  'Z01_VAR_096': { name: 'Corrente % Separador', unit: '%', description: 'Leitura corrente em Porcentagem separador dinâmico' },
  'Z01_VAR_097': { name: 'Corrente Separador', unit: 'A', description: 'Leitura corrente em amperes separador dinâmico' },
  'Z01_VAR_098': { name: 'SP Velocidade Separador', unit: 'Hz', description: 'Set-point velocidade separador dinâmico' },
  'Z01_VAR_099': { name: 'Frequência Separador', unit: 'Hz', description: 'Indicação velocidade em frequência separador dinâmico' },
  'Z01_VAR_100': { name: 'RPM Separador', unit: 'RPM', description: 'Indicação velocidade em RPM separador dinâmico' },
  'Z01_VAR_101': { name: 'Corrente % Elev Retorno', unit: '%', description: 'Leitura corrente em Porcentagem elevador de retorno' },
  'Z01_VAR_102': { name: 'Corrente Elev Retorno', unit: 'A', description: 'Leitura corrente em amperes elevador de retorno' },
  'Z01_VAR_103': { name: 'SP Velocidade Elev Ret', unit: 'Hz', description: 'Set-point velocidade elevador de retorno' },
  'Z01_VAR_104': { name: 'Frequência Elev Retorno', unit: 'Hz', description: 'Indicação velocidade em frequência elevador de retorno' },
  'Z01_VAR_105': { name: 'RPM Elev Retorno', unit: 'RPM', description: 'Indicação velocidade em RPM elevador de retorno' },
  'Z01_VAR_106': { name: 'SP Abertura Válvula Ar', unit: '%', description: 'Set-point abertura válvula ar primário do separador' },

  // MOAGEM 2 (Z02) - 106 variáveis
  'Z02_VAR_001': { name: 'Status Moinho', unit: '', description: 'Sinaliza funcionamento motor principal do moinho (1=Ligado, 0=Desligado)', isRunningIndicator: true },
  'Z02_VAR_002': { name: 'Produto Selecionado', unit: '', description: 'Seleção de produto produzido (1=CPIII 40 RS, 2=CPII E40, 3=Ensacado)' },
  'Z02_VAR_003': { name: 'Vazão Calcário %', unit: '%', description: 'Porcentagem de vazão da balança de calcário' },
  'Z02_VAR_004': { name: 'Vazão Calcário Desejada', unit: 't/h', description: 'Vazão desejada da balança de calcário' },
  'Z02_VAR_005': { name: 'Umidade Calcário', unit: '%', description: 'Umidade do material da balança de calcário' },
  'Z02_VAR_006': { name: 'Vazão Calcário Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de calcário' },
  'Z02_VAR_007': { name: 'Vazão Calcário Seca', unit: 't/h', description: 'Vazão do material base seca na balança de calcário' },
  'Z02_VAR_008': { name: 'Total Calcário Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de calcário' },
  'Z02_VAR_009': { name: 'Total Calcário Seco', unit: 't', description: 'Totalizador do material base seca na balança de calcário' },
  'Z02_VAR_010': { name: 'Vazão Gesso %', unit: '%', description: 'Porcentagem de vazão da balança de gesso' },
  'Z02_VAR_011': { name: 'Vazão Gesso Desejada', unit: 't/h', description: 'Vazão desejada da balança de gesso' },
  'Z02_VAR_012': { name: 'Umidade Gesso', unit: '%', description: 'Umidade do material da balança de gesso' },
  'Z02_VAR_013': { name: 'Vazão Gesso Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de gesso' },
  'Z02_VAR_014': { name: 'Vazão Gesso Seca', unit: 't/h', description: 'Vazão do material base seca na balança de gesso' },
  'Z02_VAR_015': { name: 'Total Gesso Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de gesso' },
  'Z02_VAR_016': { name: 'Total Gesso Seco', unit: 't', description: 'Totalizador do material base seca na balança de gesso' },
  'Z02_VAR_017': { name: 'Vazão Clínquer %', unit: '%', description: 'Porcentagem de vazão da balança de clínquer' },
  'Z02_VAR_018': { name: 'Vazão Clínquer Desejada', unit: 't/h', description: 'Vazão desejada da balança de clínquer' },
  'Z02_VAR_019': { name: 'Umidade Clínquer', unit: '%', description: 'Umidade do material da balança de clínquer' },
  'Z02_VAR_020': { name: 'Vazão Clínquer Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de clínquer' },
  'Z02_VAR_021': { name: 'Vazão Clínquer Seca', unit: 't/h', description: 'Vazão do material base seca na balança de clínquer' },
  'Z02_VAR_022': { name: 'Total Clínquer Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de clínquer' },
  'Z02_VAR_023': { name: 'Total Clínquer Seco', unit: 't', description: 'Totalizador do material base seca na balança de clínquer' },
  'Z02_VAR_024': { name: 'Vazão Escória %', unit: '%', description: 'Porcentagem de vazão da balança de escória' },
  'Z02_VAR_025': { name: 'Vazão Escória Desejada', unit: 't/h', description: 'Vazão desejada da balança de escória' },
  'Z02_VAR_026': { name: 'Umidade Escória', unit: '%', description: 'Umidade do material da balança de escória' },
  'Z02_VAR_027': { name: 'Vazão Escória Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de escória' },
  'Z02_VAR_028': { name: 'Vazão Escória Seca', unit: 't/h', description: 'Vazão do material base seca na balança de escória' },
  'Z02_VAR_029': { name: 'Total Escória Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de escória' },
  'Z02_VAR_030': { name: 'Total Escória Seco', unit: 't', description: 'Totalizador do material base seca na balança de escória' },
  'Z02_VAR_031': { name: 'Soma Total %', unit: '%', description: 'Soma total porcentagem das balanças dosadoras' },
  'Z02_VAR_032': { name: 'Soma Vazão Úmida', unit: 't/h', description: 'Soma total vazão úmida das balanças dosadoras' },
  'Z02_VAR_033': { name: 'Soma Vazão Seca', unit: 't/h', description: 'Soma total vazão seca das balanças dosadoras' },
  'Z02_VAR_034': { name: 'SP Corrente Elevador', unit: 'A', description: 'Set-point corrente elevador retorno de controle do PID' },
  'Z02_VAR_035': { name: 'SP Produção PID', unit: 't/h', description: 'Set-point de produção do moinho' },
  'Z02_VAR_036': { name: 'SP Produção Manual', unit: 't/h', description: 'Set-point manual da produção do moinho' },
  'Z02_VAR_037': { name: 'Limite Máx Produção', unit: 't/h', description: 'Limite máximo de produção do moinho' },
  'Z02_VAR_038': { name: 'Variável PID Produção', unit: 't/h', description: 'Variável PID da produção do moinho' },
  'Z02_VAR_039': { name: 'Soma Total Balanças', unit: 't', description: 'Soma do totalizador das balanças moagem 2' },
  'Z02_VAR_040': { name: 'Soma Total Consumo', unit: 't', description: 'Soma do totalizador consumo moagem 2' },
  'Z02_VAR_041': { name: 'Total Inicial Balanças', unit: 't', description: 'Totalizador inicial das balanças moagem 2' },
  'Z02_VAR_042': { name: 'Total Inicial Consumo', unit: 't', description: 'Totalizador inicial consumo moagem 2' },
  'Z02_VAR_043': { name: 'Horas Funcionamento', unit: 'h', description: 'Totalizador funcionamento (horas) do motor principal do moinho' },
  'Z02_VAR_044': { name: 'Minutos Funcionamento', unit: 'min', description: 'Totalizador funcionamento (minutos) do motor principal do moinho' },
  'Z02_VAR_045': { name: 'Segundos Funcionamento', unit: 's', description: 'Totalizador funcionamento (segundos) do motor principal do moinho' },
  'Z02_VAR_046': { name: 'Temperatura Saída', unit: '°C', description: 'Leitura temperatura de saída do moinho' },
  'Z02_VAR_047': { name: 'Pressão Entrada Filtro', unit: 'mbar', description: 'Leitura pressão entrada do filtro de processo' },
  'Z02_VAR_048': { name: 'Pressão Saída Filtro', unit: 'mbar', description: 'Leitura pressão saída do filtro de processo' },
  'Z02_VAR_049': { name: 'Temp Entrada Filtro', unit: '°C', description: 'Leitura temperatura entrada filtro de processo' },
  'Z02_VAR_050': { name: 'Pressão Saída p/ Separador', unit: 'mbar', description: 'Leitura pressão da saída do moinho para o separador' },
  'Z02_VAR_051': { name: 'Abertura Válvula Ar', unit: '%', description: 'Leitura abertura válvula ar primário do separador' },
  'Z02_VAR_052': { name: 'Pressão Diferencial Filtro', unit: 'mbar', description: 'Leitura pressão diferencial do filtro de processo' },
  'Z02_VAR_053': { name: 'Temp Falta Alimentação', unit: 's', description: 'Temporização falta de alimentação do moinho' },
  'Z02_VAR_054': { name: 'Consumo Energia Motor', unit: 'kWh', description: 'Totalizador de Consumo de Energia do Motor do moinho' },
  'Z02_VAR_055': { name: 'Consumo Energia CCM2', unit: 'kWh', description: 'Totalizador de Consumo de Energia do CCM 2' },
  'Z02_VAR_056': { name: 'Tensão L1-N CCM2', unit: 'V', description: 'Leitura tensão entre L1 e neutro do CCM 2' },
  'Z02_VAR_057': { name: 'Tensão L2-N CCM2', unit: 'V', description: 'Leitura tensão entre L2 e neutro do CCM 2' },
  'Z02_VAR_058': { name: 'Tensão L3-N CCM2', unit: 'V', description: 'Leitura tensão entre L3 e neutro do CCM 2' },
  'Z02_VAR_059': { name: 'Tensão L1-L2 CCM2', unit: 'V', description: 'Leitura tensão entre L1 e L2 do CCM 2' },
  'Z02_VAR_060': { name: 'Tensão L2-L3 CCM2', unit: 'V', description: 'Leitura tensão entre L2 e L3 do CCM 2' },
  'Z02_VAR_061': { name: 'Tensão L1-L3 CCM2', unit: 'V', description: 'Leitura tensão entre L1 e L3 do CCM 2' },
  'Z02_VAR_062': { name: 'Corrente L1 CCM2', unit: 'A', description: 'Leitura corrente em L1 do CCM 2' },
  'Z02_VAR_063': { name: 'Corrente L2 CCM2', unit: 'A', description: 'Leitura corrente em L2 do CCM 2' },
  'Z02_VAR_064': { name: 'Corrente L3 CCM2', unit: 'A', description: 'Leitura corrente em L3 do CCM 2' },
  'Z02_VAR_065': { name: 'Potência Ativa CCM2', unit: 'kW', description: 'Leitura potência ativa total do CCM 2' },
  'Z02_VAR_066': { name: 'Potência Reativa CCM2', unit: 'kVAr', description: 'Leitura potência reativa total do CCM 2' },
  'Z02_VAR_067': { name: 'Demanda Potência CCM2', unit: 'kW', description: 'Leitura demanda potência ativa do CCM 2' },
  'Z02_VAR_068': { name: 'Fator Potência CCM2', unit: '', description: 'Leitura fator de potência total do CCM 2' },
  // VAR_069: val(78) está COMENTADO no script VB - não existe no arquivo!
  'Z02_VAR_069': { name: 'Silo Selecionado', unit: '', description: 'Seleção de produção do moinho (1=Silo 1, 2=Silo 2, 3=Silo 3, 4=Silo 4)' },
  'Z02_VAR_070': { name: 'Tensão L1-N Motor', unit: 'V', description: 'Leitura tensão entre L1 e neutro do Motor principal do moinho' },
  'Z02_VAR_071': { name: 'Tensão L2-N Motor', unit: 'V', description: 'Leitura tensão entre L2 e neutro do Motor principal do moinho' },
  'Z02_VAR_072': { name: 'Tensão L3-N Motor', unit: 'V', description: 'Leitura tensão entre L3 e neutro do Motor principal do moinho' },
  'Z02_VAR_073': { name: 'Tensão L1-L2 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L2 do Motor principal do moinho' },
  'Z02_VAR_074': { name: 'Tensão L2-L3 Motor', unit: 'V', description: 'Leitura tensão entre L2 e L3 do Motor principal do moinho' },
  'Z02_VAR_075': { name: 'Tensão L1-L3 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L3 do Motor principal do moinho' },
  'Z02_VAR_076': { name: 'Corrente L1 Motor', unit: 'A', description: 'Leitura corrente em L1 do Motor principal do moinho' },
  'Z02_VAR_077': { name: 'Fator Potência CCM2', unit: '', description: 'Leitura fator de potência total do CCM 1' },
  // Z02_VAR_078 não existe - está comentada no script VB
  'Z02_VAR_079': { name: 'Silo Selecionado', unit: '', description: 'Seleção de produção do moinho (1-Silo1, 2-Silo2, 3-Silo3, 4-Silo4)' },
  'Z02_VAR_080': { name: 'Tensão L1-N Motor', unit: 'V', description: 'Leitura tensão entre L1 e neutro do Motor principal do moinho' },
  'Z02_VAR_081': { name: 'Tensão L2-N Motor', unit: 'V', description: 'Leitura tensão entre L2 e neutro do Motor principal do moinho' },
  'Z02_VAR_082': { name: 'Tensão L3-N Motor', unit: 'V', description: 'Leitura tensão entre L3 e neutro do Motor principal do moinho' },
  'Z02_VAR_083': { name: 'Tensão L1-L2 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L2 do Motor principal do moinho' },
  'Z02_VAR_084': { name: 'Tensão L2-L3 Motor', unit: 'V', description: 'Leitura tensão entre L2 e L3 do Motor principal do moinho' },
  'Z02_VAR_085': { name: 'Tensão L1-L3 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L3 do Motor principal do moinho' },
  'Z02_VAR_086': { name: 'Corrente L1 Motor', unit: 'A', description: 'Leitura corrente em L1 do Motor principal do moinho' },
  'Z02_VAR_087': { name: 'Corrente L2 Motor', unit: 'A', description: 'Leitura corrente em L2 do Motor principal do moinho' },
  'Z02_VAR_088': { name: 'Corrente L3 Motor', unit: 'A', description: 'Leitura corrente em L3 do Motor principal do moinho' },
  'Z02_VAR_089': { name: 'Potência Ativa Motor', unit: 'kW', description: 'Leitura potência ativa total do Motor principal do moinho' },
  'Z02_VAR_090': { name: 'Potência Reativa Motor', unit: 'kVAr', description: 'Leitura potência reativa total do Motor principal do moinho' },
  'Z02_VAR_091': { name: 'Demanda Potência Motor', unit: 'kW', description: 'Leitura demanda potência ativa do Motor principal do moinho' },
  'Z02_VAR_092': { name: 'Fator Potência Motor', unit: '', description: 'Leitura fator de potência total do Motor principal do moinho' },
  'Z02_VAR_093': { name: 'Energia Consumida Motor', unit: 'kWh', description: 'Leitura Energia consumida do Motor principal do moinho' },
  'Z02_VAR_094': { name: 'Corrente % Motor', unit: '%', description: 'Leitura corrente em Porcentagem Motor principal moinho' },
  'Z02_VAR_095': { name: 'Corrente % Elevador Proc', unit: '%', description: 'Leitura corrente em Porcentagem elevador de processo' },
  'Z02_VAR_096': { name: 'Corrente Elevador Proc', unit: 'A', description: 'Leitura corrente em amperes elevador de processo' },
  'Z02_VAR_097': { name: 'SP Velocidade Elevador', unit: 'Hz', description: 'Set-point velocidade elevador de processo' },
  'Z02_VAR_098': { name: 'Frequência Elevador', unit: 'Hz', description: 'Indicação velocidade em frequência elevador de processo' },
  'Z02_VAR_099': { name: 'RPM Elevador Processo', unit: 'RPM', description: 'Indicação velocidade em RPM elevador de processo' },
  'Z02_VAR_100': { name: 'Corrente % Vent Filtro', unit: '%', description: 'Leitura corrente em Porcentagem ventilador filtro de processo' },
  'Z02_VAR_101': { name: 'Corrente Vent Filtro', unit: 'A', description: 'Leitura corrente em amperes ventilador filtro de processo' },
  'Z02_VAR_102': { name: 'SP Velocidade Vent Filtro', unit: 'Hz', description: 'Set-point velocidade ventilador filtro de processo' },
  'Z02_VAR_103': { name: 'Frequência Vent Filtro', unit: 'Hz', description: 'Indicação velocidade em frequência ventilador filtro de processo' },
  'Z02_VAR_104': { name: 'RPM Vent Filtro', unit: 'RPM', description: 'Indicação velocidade em RPM ventilador filtro de processo' },
  'Z02_VAR_105': { name: 'Corrente Separador', unit: 'A', description: 'Leitura corrente em amperes separador dinâmico' },
  'Z02_VAR_106': { name: 'Corrente % Separador', unit: '%', description: 'Leitura corrente em porcentagem separador dinâmico' },
  'Z02_VAR_107': { name: 'SP Velocidade Separador', unit: 'Hz', description: 'Set-point velocidade separador dinâmico' },
  'Z02_VAR_108': { name: 'Frequência Separador', unit: 'Hz', description: 'Indicação velocidade em frequência separador dinâmico' },
  'Z02_VAR_109': { name: 'RPM Separador', unit: 'RPM', description: 'Indicação velocidade em RPM separador dinâmico' },
  'Z02_VAR_110': { name: 'Corrente Elev Retorno', unit: 'A', description: 'Leitura corrente em amperes elevador de retorno' },
  'Z02_VAR_111': { name: 'Corrente % Elev Retorno', unit: '%', description: 'Leitura corrente em porcentagem elevador de retorno' },
  'Z02_VAR_112': { name: 'SP Velocidade Elev Ret', unit: 'Hz', description: 'Set-point velocidade elevador de retorno' },
  'Z02_VAR_113': { name: 'Frequência Elev Retorno', unit: 'Hz', description: 'Indicação velocidade em frequência elevador de retorno' },
  'Z02_VAR_114': { name: 'RPM Elev Retorno', unit: 'RPM', description: 'Indicação velocidade em RPM elevador de retorno' },
  'Z02_VAR_115': { name: 'SP Abertura Válvula Ar', unit: '%', description: 'Set-point abertura válvula ar primário do separador' },

  // MOAGEM 3 (Z03) - 97 variáveis
  'Z03_VAR_001': { name: 'Status Moinho', unit: '', description: 'Sinaliza funcionamento motor principal do moinho (1=Ligado, 0=Desligado)', isRunningIndicator: true },
  'Z03_VAR_002': { name: 'Vazão Calcário %', unit: '%', description: 'Porcentagem de vazão da balança de calcário' },
  'Z03_VAR_003': { name: 'Umidade Calcário', unit: '%', description: 'Umidade do material da balança de calcário' },
  'Z03_VAR_004': { name: 'Vazão Calcário Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de calcário' },
  'Z03_VAR_005': { name: 'Vazão Calcário Seca', unit: 't/h', description: 'Vazão do material base seca na balança de calcário' },
  'Z03_VAR_006': { name: 'Total Calcário Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de calcário' },
  'Z03_VAR_007': { name: 'Vazão Gesso %', unit: '%', description: 'Porcentagem de vazão da balança de gesso' },
  'Z03_VAR_008': { name: 'Vazão Gesso Desejada', unit: 't/h', description: 'Vazão desejada da balança de gesso' },
  'Z03_VAR_009': { name: 'Umidade Gesso', unit: '%', description: 'Umidade do material da balança de gesso' },
  'Z03_VAR_010': { name: 'Vazão Gesso Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de gesso' },
  'Z03_VAR_011': { name: 'Vazão Gesso Seca', unit: 't/h', description: 'Vazão do material base seca na balança de gesso' },
  'Z03_VAR_012': { name: 'Total Gesso Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de gesso' },
  'Z03_VAR_013': { name: 'Vazão Clínquer %', unit: '%', description: 'Porcentagem de vazão da balança de clínquer' },
  'Z03_VAR_014': { name: 'Vazão Clínquer Desejada', unit: 't/h', description: 'Vazão desejada da balança de clínquer' },
  'Z03_VAR_015': { name: 'Umidade Clínquer', unit: '%', description: 'Umidade do material da balança de clínquer' },
  'Z03_VAR_016': { name: 'Vazão Clínquer Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de clínquer' },
  'Z03_VAR_017': { name: 'Vazão Clínquer Seca', unit: 't/h', description: 'Vazão do material base seca na balança de clínquer' },
  'Z03_VAR_018': { name: 'Total Clínquer Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de clínquer' },
  'Z03_VAR_019': { name: 'Vazão Escória %', unit: '%', description: 'Porcentagem de vazão da balança de escória' },
  'Z03_VAR_020': { name: 'Vazão Escória Desejada', unit: 't/h', description: 'Vazão desejada da balança de escória' },
  'Z03_VAR_021': { name: 'Umidade Escória', unit: '%', description: 'Umidade do material da balança de escória' },
  'Z03_VAR_022': { name: 'Vazão Escória Úmida', unit: 't/h', description: 'Vazão do material base úmida na balança de escória' },
  'Z03_VAR_023': { name: 'Vazão Escória Seca', unit: 't/h', description: 'Vazão do material base seca na balança de escória' },
  'Z03_VAR_024': { name: 'Total Escória Úmido', unit: 't', description: 'Totalizador do material base úmida na balança de escória' },
  'Z03_VAR_025': { name: 'Soma Total %', unit: '%', description: 'Soma total porcentagem das balanças dosadoras' },
  'Z03_VAR_026': { name: 'Soma Vazão Úmida', unit: 't/h', description: 'Soma total vazão úmida das balanças dosadoras' },
  'Z03_VAR_027': { name: 'Soma Vazão Seca', unit: 't/h', description: 'Soma total vazão seca das balanças dosadoras' },
  'Z03_VAR_028': { name: 'SP Corrente Elevador', unit: 'A', description: 'Set-point corrente elevador retorno de controle do PID alimentação moinho' },
  'Z03_VAR_029': { name: 'SP Produção Moinho', unit: 't/h', description: 'Set-point de produção do moinho' },
  'Z03_VAR_030': { name: 'SP Produção Manual', unit: 't/h', description: 'Set-point manual da produção do moinho' },
  'Z03_VAR_031': { name: 'Limite Máx Produção', unit: 't/h', description: 'Limite máximo de produção do moinho' },
  'Z03_VAR_032': { name: 'Variável PID Produção', unit: 't/h', description: 'Variável PID da produção do moinho' },
  'Z03_VAR_033': { name: 'Pedido Vel Local Calcário', unit: 'Hz', description: 'Pedido de velocidade em local da balança de calcário' },
  'Z03_VAR_034': { name: 'Pedido Vel Local Gesso', unit: 'Hz', description: 'Pedido de velocidade em local da balança de gesso' },
  'Z03_VAR_035': { name: 'Pedido Vel Local Clínquer', unit: 'Hz', description: 'Pedido de velocidade em local da balança de clínquer' },
  'Z03_VAR_036': { name: 'Pedido Vel Local Escória', unit: 'Hz', description: 'Pedido de velocidade em local da balança de escória' },
  'Z03_VAR_037': { name: 'Minutos Funcionamento', unit: 'min', description: 'Totalizador funcionamento (minutos) do motor principal do moinho' },
  'Z03_VAR_038': { name: 'Segundos Funcionamento', unit: 's', description: 'Totalizador funcionamento (segundos) do motor principal do moinho' },
  'Z03_VAR_039': { name: 'Temperatura Saída', unit: '°C', description: 'Leitura temperatura de saída do moinho' },
  'Z03_VAR_040': { name: 'Pressão Entrada Filtro', unit: 'mbar', description: 'Leitura pressão entrada do filtro de processo' },
  'Z03_VAR_041': { name: 'Pressão Saída Filtro', unit: 'mbar', description: 'Leitura pressão saída do filtro de processo' },
  'Z03_VAR_042': { name: 'Temp Entrada Filtro', unit: '°C', description: 'Leitura temperatura entrada filtro de processo' },
  'Z03_VAR_043': { name: 'Temp Saída p/ Separador', unit: '°C', description: 'Leitura temperatura da saída do moinho para o separador' },
  'Z03_VAR_044': { name: 'Pressão Saída p/ Separador', unit: 'mbar', description: 'Leitura pressão da saída do moinho para o separador' },
  'Z03_VAR_045': { name: 'Abertura Válvula Ar Prim', unit: '%', description: 'Leitura abertura válvula ar primário do separador' },
  'Z03_VAR_046': { name: 'Abertura Válvula Ar Sec', unit: '%', description: 'Leitura abertura válvula ar secundário do separador' },
  'Z03_VAR_047': { name: 'Abertura Válvula Ar Filtro', unit: '%', description: 'Leitura abertura válvula ar filtro de processo' },
  'Z03_VAR_048': { name: 'Pressão Diferencial Filtro', unit: 'mbar', description: 'Leitura pressão diferencial do filtro de processo' },
  'Z03_VAR_049': { name: 'Consumo Energia Motor', unit: 'kWh', description: 'Totalizador de Consumo de Energia do motor do moinho' },
  'Z03_VAR_050': { name: 'Consumo Energia CCM3', unit: 'kWh', description: 'Totalizador de Consumo de Energia do CCM 3' },
  'Z03_VAR_051': { name: 'Soma Total Balanças', unit: 't', description: 'Soma total dos totalizadores' },
  'Z03_VAR_052': { name: 'Total Inicial', unit: 't', description: 'Totalizador inicial balanças' },
  'Z03_VAR_053': { name: 'Total Acumulado', unit: 't', description: 'Totalizador acumulado' },
  'Z03_VAR_054': { name: 'Tensão L1-N CCM5', unit: 'V', description: 'Leitura tensão entre L1 e neutro do CCM 5' },
  'Z03_VAR_055': { name: 'Tensão L2-N CCM5', unit: 'V', description: 'Leitura tensão entre L2 e neutro do CCM 5' },
  'Z03_VAR_056': { name: 'Tensão L3-N CCM5', unit: 'V', description: 'Leitura tensão entre L3 e neutro do CCM 5' },
  'Z03_VAR_057': { name: 'Tensão L1-L2 CCM5', unit: 'V', description: 'Leitura tensão entre L1 e L2 do CCM 5' },
  'Z03_VAR_058': { name: 'Tensão L2-L3 CCM5', unit: 'V', description: 'Leitura tensão entre L2 e L3 do CCM 5' },
  'Z03_VAR_059': { name: 'Tensão L1-L3 CCM5', unit: 'V', description: 'Leitura tensão entre L1 e L3 do CCM 5' },
  'Z03_VAR_060': { name: 'Corrente L1 CCM5', unit: 'A', description: 'Leitura corrente em L1 do CCM 5' },
  'Z03_VAR_061': { name: 'Corrente L2 CCM5', unit: 'A', description: 'Leitura corrente em L2 do CCM 5' },
  'Z03_VAR_062': { name: 'Corrente L3 CCM5', unit: 'A', description: 'Leitura corrente em L3 do CCM 5' },
  'Z03_VAR_063': { name: 'Potência Ativa CCM5', unit: 'kW', description: 'Leitura potência ativa total do CCM 5' },
  'Z03_VAR_064': { name: 'Potência Reativa CCM5', unit: 'kVAr', description: 'Leitura potência reativa total do CCM 5' },
  'Z03_VAR_065': { name: 'Demanda Potência CCM5', unit: 'kW', description: 'Leitura demanda potência ativa do CCM 5' },
  'Z03_VAR_066': { name: 'Fator Potência CCM5', unit: '', description: 'Leitura fator de potência total do CCM 5' },
  'Z03_VAR_067': { name: 'Energia Consumida CCM5', unit: 'kWh', description: 'Leitura Energia consumida do CCM 5' },
  'Z03_VAR_068': { name: 'Produto Selecionado', unit: '', description: 'Produto produzido (1=CPIII 40 RS, 2=CPII E40, 3=Ensacado)' },
  'Z03_VAR_069': { name: 'Silo Selecionado', unit: '', description: 'Seleção de produção do moinho (1=Silo 1, 2=Silo 2, 3=Silo 3, 4=Silo 4)' },
  'Z03_VAR_070': { name: 'Status Moinho Float', unit: '', description: 'Sinaliza funcionamento motor principal do moinho (1=Ligado, 0=Desligado)' },
  'Z03_VAR_071': { name: 'Tensão L1-N Motor', unit: 'V', description: 'Leitura tensão entre L1 e neutro do motor principal do moinho' },
  'Z03_VAR_072': { name: 'Tensão L2-N Motor', unit: 'V', description: 'Leitura tensão entre L2 e neutro do motor principal do moinho' },
  'Z03_VAR_073': { name: 'Tensão L3-N Motor', unit: 'V', description: 'Leitura tensão entre L3 e neutro do motor principal do moinho' },
  'Z03_VAR_074': { name: 'Tensão L1-L2 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L2 do motor principal do moinho' },
  'Z03_VAR_075': { name: 'Tensão L2-L3 Motor', unit: 'V', description: 'Leitura tensão entre L2 e L3 do motor principal do moinho' },
  'Z03_VAR_076': { name: 'Tensão L1-L3 Motor', unit: 'V', description: 'Leitura tensão entre L1 e L3 do motor principal do moinho' },
  'Z03_VAR_077': { name: 'Corrente L1 Motor', unit: 'A', description: 'Leitura corrente em L1 do motor principal do moinho' },
  'Z03_VAR_078': { name: 'Corrente L2 Motor', unit: 'A', description: 'Leitura corrente em L2 do motor principal do moinho' },
  'Z03_VAR_079': { name: 'Corrente L3 Motor', unit: 'A', description: 'Leitura corrente em L3 do motor principal do moinho' },
  'Z03_VAR_080': { name: 'Potência Ativa Motor', unit: 'kW', description: 'Leitura potência ativa total do motor principal do moinho' },
  'Z03_VAR_081': { name: 'Potência Reativa Motor', unit: 'kVAr', description: 'Leitura potência reativa total do motor principal do moinho' },
  'Z03_VAR_082': { name: 'Demanda Potência Motor', unit: 'kW', description: 'Leitura demanda potência ativa do motor principal do moinho' },
  'Z03_VAR_083': { name: 'Fator Potência Motor', unit: '', description: 'Leitura fator de potência total do motor principal do moinho' },
  'Z03_VAR_084': { name: 'Energia Consumida Motor', unit: 'kWh', description: 'Leitura Energia consumida do motor principal do moinho' },
  'Z03_VAR_085': { name: 'Corrente % Motor', unit: '%', description: 'Leitura corrente em Porcentagem' },
  'Z03_VAR_086': { name: 'Corrente % Vent Filtro', unit: '%', description: 'Leitura corrente em Porcentagem ventilador filtro de processo' },
  'Z03_VAR_087': { name: 'Corrente Vent Filtro', unit: 'A', description: 'Leitura corrente em amperes ventilador filtro de processo' },
  'Z03_VAR_088': { name: 'Corrente % Separador', unit: '%', description: 'Leitura corrente em Porcentagem separador dinâmico' },
  'Z03_VAR_089': { name: 'Corrente Separador', unit: 'A', description: 'Leitura corrente em amperes separador dinâmico' },
  'Z03_VAR_090': { name: 'SP Velocidade Separador', unit: 'Hz', description: 'Set-point velocidade separador dinâmico' },
  'Z03_VAR_091': { name: 'Frequência Separador', unit: 'Hz', description: 'Indicação velocidade em frequência separador dinâmico' },
  'Z03_VAR_092': { name: 'RPM Separador', unit: 'RPM', description: 'Indicação velocidade em RPM separador dinâmico' },
  'Z03_VAR_093': { name: 'Corrente % Elev Retorno', unit: '%', description: 'Leitura corrente em Porcentagem elevador de retorno' },
  'Z03_VAR_094': { name: 'Corrente Elev Retorno', unit: 'A', description: 'Leitura corrente em amperes elevador de retorno' },
  'Z03_VAR_095': { name: 'SP Abertura Válvula Ar Prim', unit: '%', description: 'Set-point abertura válvula ar primário do separador' },
  'Z03_VAR_096': { name: 'SP Abertura Válvula Ar Sec', unit: '%', description: 'Set-point abertura válvula ar secundário do separador' },
  'Z03_VAR_097': { name: 'SP Abertura Válvula Ar Filtro', unit: '%', description: 'Set-point abertura válvula motorizada ar filtro de processo' },

  // SECADOR (S01) - 77 variáveis
  'S01_VAR_01': { name: 'Status Secador', unit: '', description: 'Sinaliza funcionando Secador de Escória (1=Ligado, 0=Desligado)', isRunningIndicator: true },
  'S01_VAR_02': { name: 'Temp Saída Queimador', unit: '°C', description: 'Leitura temperatura na saída do queimador de cavacos' },
  'S01_VAR_03': { name: 'Temp Entrada Secador', unit: '°C', description: 'Leitura temperatura na entrada do secador de escória' },
  'S01_VAR_04': { name: 'Pressão Ar Comprimido', unit: 'bar', description: 'Leitura pressão do ar comprimido na saída do compressor' },
  'S01_VAR_05': { name: 'Temp Sala CCM', unit: '°C', description: 'Leitura temperatura na sala do CCM' },
  'S01_VAR_06': { name: 'Posição Válvula Ar Frio', unit: '%', description: 'Leitura posição válvula motorizada ar frio da entrada do filtro do secador' },
  'S01_VAR_07': { name: 'Peso Silo Cavacos', unit: 't', description: 'Leitura peso do silo de cavacos' },
  'S01_VAR_08': { name: 'SP Produção Secador', unit: 't/h', description: 'Valor inserido no set-point de T/h da produção do secador de escória' },
  'S01_VAR_09': { name: 'Pressão Dif Filtro Clínquer', unit: 'mbar', description: 'Leitura pressão diferencial do filtro despoeiramento silo de clínquer' },
  'S01_VAR_10': { name: 'Pressão Dif Filtro Secador', unit: 'mbar', description: 'Leitura pressão diferencial do filtro do secador de escória' },
  'S01_VAR_11': { name: 'Tensão L1-N CCM4', unit: 'V', description: 'Leitura tensão entre L1 e neutro do CCM 4' },
  'S01_VAR_12': { name: 'Tensão L2-N CCM4', unit: 'V', description: 'Leitura tensão entre L2 e neutro do CCM 4' },
  'S01_VAR_13': { name: 'Tensão L3-N CCM4', unit: 'V', description: 'Leitura tensão entre L3 e neutro do CCM 4' },
  'S01_VAR_14': { name: 'Tensão L1-L2 CCM4', unit: 'V', description: 'Leitura tensão entre L1 e L2 do CCM 4' },
  'S01_VAR_15': { name: 'Tensão L2-L3 CCM4', unit: 'V', description: 'Leitura tensão entre L2 e L3 do CCM 4' },
  'S01_VAR_16': { name: 'Tensão L1-L3 CCM4', unit: 'V', description: 'Leitura tensão entre L1 e L3 do CCM 4' },
  'S01_VAR_17': { name: 'Corrente L1 CCM4', unit: 'A', description: 'Leitura corrente em L1 do CCM 4' },
  'S01_VAR_18': { name: 'Corrente L2 CCM4', unit: 'A', description: 'Leitura corrente em L2 do CCM 4' },
  'S01_VAR_19': { name: 'Corrente L3 CCM4', unit: 'A', description: 'Leitura corrente em L3 do CCM 4' },
  'S01_VAR_20': { name: 'Potência Ativa CCM4', unit: 'kW', description: 'Leitura potência ativa total do CCM 4' },
  'S01_VAR_21': { name: 'Potência Reativa CCM4', unit: 'kVAr', description: 'Leitura potência reativa total do CCM 4' },
  'S01_VAR_22': { name: 'Demanda Potência CCM4', unit: 'kW', description: 'Leitura demanda potência ativa do CCM 4' },
  'S01_VAR_23': { name: 'Fator Potência CCM4', unit: '', description: 'Leitura fator de potência total do CCM 4' },
  'S01_VAR_24': { name: 'Energia Consumida CCM4', unit: 'kWh', description: 'Leitura energia consumida do CCM 4' },
  'S01_VAR_25': { name: 'Tensão L1-N QDF', unit: 'V', description: 'Leitura tensão entre L1 e neutro do QDF' },
  'S01_VAR_26': { name: 'Tensão L2-N QDF', unit: 'V', description: 'Leitura tensão entre L2 e neutro do QDF' },
  'S01_VAR_27': { name: 'Tensão L3-N QDF', unit: 'V', description: 'Leitura tensão entre L3 e neutro do QDF' },
  'S01_VAR_28': { name: 'Tensão L1-L2 QDF', unit: 'V', description: 'Leitura tensão entre L1 e L2 do QDF' },
  'S01_VAR_29': { name: 'Tensão L2-L3 QDF', unit: 'V', description: 'Leitura tensão entre L2 e L3 do QDF' },
  'S01_VAR_30': { name: 'Tensão L1-L3 QDF', unit: 'V', description: 'Leitura tensão entre L1 e L3 do QDF' },
  'S01_VAR_31': { name: 'Corrente L1 QDF', unit: 'A', description: 'Leitura corrente em L1 do QDF' },
  'S01_VAR_32': { name: 'Corrente L2 QDF', unit: 'A', description: 'Leitura corrente em L2 do QDF' },
  'S01_VAR_33': { name: 'Corrente L3 QDF', unit: 'A', description: 'Leitura corrente em L3 do QDF' },
  'S01_VAR_34': { name: 'Potência Ativa QDF', unit: 'kW', description: 'Leitura potência ativa total do QDF' },
  'S01_VAR_35': { name: 'Potência Reativa QDF', unit: 'kVAr', description: 'Leitura potência reativa total do QDF' },
  'S01_VAR_36': { name: 'Demanda Potência QDF', unit: 'kW', description: 'Leitura demanda potência ativa do QDF' },
  'S01_VAR_37': { name: 'Fator Potência QDF', unit: '', description: 'Leitura fator de potência total do QDF' },
  'S01_VAR_38': { name: 'Energia Consumida QDF', unit: 'kWh', description: 'Leitura energia consumida do QDF' },
  'S01_VAR_39': { name: 'Corrente % Vent Filtro', unit: '%', description: 'Leitura corrente em porcentagem Ventilador do Filtro Processo do Secador' },
  'S01_VAR_40': { name: 'Corrente Vent Filtro', unit: 'A', description: 'Leitura corrente em amperes Ventilador do Filtro Processo do Secador' },
  'S01_VAR_41': { name: 'SP Velocidade Vent Filtro', unit: 'Hz', description: 'Set-point velocidade Ventilador do Filtro Processo do Secador' },
  'S01_VAR_42': { name: 'Frequência Vent Filtro', unit: 'Hz', description: 'Indicação velocidade em frequência Ventilador do Filtro Processo do Secador' },
  'S01_VAR_43': { name: 'RPM Vent Filtro', unit: 'RPM', description: 'Indicação velocidade em RPM Ventilador do Filtro Processo do Secador' },
  'S01_VAR_44': { name: 'Corrente % Secador', unit: '%', description: 'Leitura corrente em porcentagem Secador de Escória' },
  'S01_VAR_45': { name: 'Corrente Secador', unit: 'A', description: 'Leitura corrente em amperes Secador de Escória' },
  'S01_VAR_46': { name: 'SP Velocidade Secador', unit: 'Hz', description: 'Set-point velocidade Secador de Escória' },
  'S01_VAR_47': { name: 'Frequência Secador', unit: 'Hz', description: 'Indicação velocidade em frequência Secador de Escória' },
  'S01_VAR_48': { name: 'RPM Secador', unit: 'RPM', description: 'Indicação velocidade em RPM Secador de Escória' },
  'S01_VAR_49': { name: 'Corrente % Vent Ar Combustão', unit: '%', description: 'Leitura corrente em porcentagem Ventilador Ar Combustão do Queimador Cavacos' },
  'S01_VAR_50': { name: 'Corrente Vent Ar Combustão', unit: 'A', description: 'Leitura corrente em amperes Ventilador Ar Combustão do Queimador Cavacos' },
  'S01_VAR_51': { name: 'SP Velocidade Vent Ar Comb', unit: 'Hz', description: 'Set-point velocidade Ventilador Ar Combustão do Queimador Cavacos' },
  'S01_VAR_52': { name: 'Frequência Vent Ar Comb', unit: 'Hz', description: 'Indicação velocidade em frequência Ventilador Ar Combustão do Queimador Cavacos' },
  'S01_VAR_53': { name: 'RPM Vent Ar Combustão', unit: 'RPM', description: 'Indicação velocidade em RPM Ventilador Ar Combustão do Queimador Cavacos' },
  'S01_VAR_54': { name: 'Corrente % Rosca Dosadora', unit: '%', description: 'Leitura corrente em porcentagem Rosca Dosadora do Queimador Cavacos' },
  'S01_VAR_55': { name: 'Corrente Rosca Dosadora', unit: 'A', description: 'Leitura corrente em amperes Rosca Dosadora do Queimador Cavacos' },
  'S01_VAR_56': { name: 'SP Velocidade Rosca Dosadora', unit: 'Hz', description: 'Set-point velocidade Rosca Dosadora do Queimador Cavacos' },
  'S01_VAR_57': { name: 'Frequência Rosca Dosadora', unit: 'Hz', description: 'Indicação velocidade em frequência Rosca Dosadora do Queimador Cavacos' },
  'S01_VAR_58': { name: 'RPM Rosca Dosadora', unit: 'RPM', description: 'Indicação velocidade em RPM Rosca Dosadora do Queimador Cavacos' },
  'S01_VAR_59': { name: 'Corrente % Correia Alim', unit: '%', description: 'Leitura corrente em porcentagem Correia Alimentação do Silo de Cavacos' },
  'S01_VAR_60': { name: 'Corrente Correia Alim', unit: 'A', description: 'Leitura corrente em amperes Correia Alimentação do Silo de Cavacos' },
  'S01_VAR_61': { name: 'SP Velocidade Correia Alim', unit: 'Hz', description: 'Set-point velocidade Correia Alimentação do Silo de Cavacos' },
  'S01_VAR_62': { name: 'Frequência Correia Alim', unit: 'Hz', description: 'Indicação velocidade em frequência Correia Alimentação do Silo de Cavacos' },
  'S01_VAR_63': { name: 'RPM Correia Alimentação', unit: 'RPM', description: 'Indicação velocidade em amperes Correia Alimentação do Silo de Cavacos' },
  'S01_VAR_64': { name: 'Corrente % Balança Dosadora', unit: '%', description: 'Leitura corrente em porcentagem Balança Dosadora do Secador de Escória' },
  'S01_VAR_65': { name: 'Corrente Balança Dosadora', unit: 'A', description: 'Leitura corrente em amperes Balança Dosadora do Secador de Escória' },
  'S01_VAR_66': { name: 'SP Vel Balança Miltronics', unit: 'Hz', description: 'Set-point velocidade Balança Dosadora do Secador de Escória (Miltronics)' },
  'S01_VAR_67': { name: 'Frequência Balança Dosadora', unit: 'Hz', description: 'Indicação velocidade em frequência Balança Dosadora do Secador de Escória' },
  'S01_VAR_68': { name: 'RPM Balança Dosadora', unit: 'RPM', description: 'Indicação velocidade em RPM Balança Dosadora do Secador de Escória' },
  'S01_VAR_69': { name: 'SP Vel Balança %', unit: '%', description: 'Set-point velocidade Balança Dosadora do Secador de Escória (Porcentagem)' },
  'S01_VAR_70': { name: 'Matéria Prima Secador', unit: '', description: 'Matéria prima produzida pelo secador (Sempre escória - 51)' },
  'S01_VAR_71': { name: 'Seleção Silo Escória', unit: '', description: 'Seleção de silo escória (5=Silo Calcário, 6=Silo Gesso, 7=Silo Clínquer, 8=Silo de Escória)' },
  'S01_VAR_72': { name: 'Total Queimador Cavaco', unit: 't', description: 'Totalizador do queimador de cavaco (Ton)' },
  'S01_VAR_73': { name: 'Total Secador Escória', unit: 't', description: 'Totalizador do secador de escória (Ton)' },
  'S01_VAR_74': { name: 'Pressão Dif Filtro Silo Escória', unit: 'mbar', description: 'Diferencial do filtro de despoeiramento do silo de escória L1P05' },
  'S01_VAR_75': { name: 'Pressão Dif Filtro Secador E1P01', unit: 'mbar', description: 'Diferencial filtro secador E1P01' },
  'S01_VAR_76': { name: 'Vazão Escória Úmida', unit: 't/h', description: 'Vazão escória úmida instantânea' },
  'S01_VAR_77': { name: 'Vazão Escória Seca', unit: 't/h', description: 'Vazão escória seca instantânea' },

  // ENERGIA (ENE) - 12 variáveis
  'ENE_VAR_009': { name: 'Status Energia', unit: '', description: 'Status do sistema de energia (1.0=Ativo)' },
  'ENE_VAR_010': { name: 'Consumo MC1', unit: 'kWh', description: 'Consumo de energia Moinho de Cimento 1' },
  'ENE_VAR_011': { name: 'Consumo MC2', unit: 'kWh', description: 'Consumo de energia Moinho de Cimento 2' },
  'ENE_VAR_012': { name: 'Consumo MC3', unit: 'kWh', description: 'Consumo de energia Moinho de Cimento 3' },
  'ENE_VAR_013': { name: 'Consumo CCM1', unit: 'kWh', description: 'Consumo CCM1 - Moagem 1' },
  'ENE_VAR_014': { name: 'Consumo CCM2', unit: 'kWh', description: 'Consumo CCM2 - Moagem 2 (não utilizado)' },
  'ENE_VAR_015': { name: 'Consumo CCM3', unit: 'kWh', description: 'Consumo CCM3 - Expedição' },
  'ENE_VAR_016': { name: 'Consumo CCM4', unit: 'kWh', description: 'Consumo CCM4 - Utilidades' },
  'ENE_VAR_017': { name: 'Consumo CCM5', unit: 'kWh', description: 'Consumo CCM5 - Moagem 3' },
  'ENE_VAR_018': { name: 'Tensão L1-L2', unit: 'V', description: 'Tensão entre L1 e L2 da entrada geral' },
  'ENE_VAR_019': { name: 'Tensão L2-L3', unit: 'V', description: 'Tensão entre L2 e L3 da entrada geral' },
  'ENE_VAR_020': { name: 'Tensão L1-L3', unit: 'V', description: 'Tensão entre L1 e L3 da entrada geral' },

  // ENSACADEIRA 2 (EN2) - 20 variáveis
  'EN2_VAR_010': { name: 'Status Ensacadeira 2', unit: '', description: 'Sinaliza funcionamento Ensacadeira 2 (1=Ligado, 2=Desligado)', isRunningIndicator: true },
  'EN2_VAR_011': { name: 'Corrente % Elevador Ens2', unit: '%', description: 'Leitura corrente em porcentagem elevador da ensacadeira 2' },
  'EN2_VAR_012': { name: 'Corrente Elevador Ens2', unit: 'A', description: 'Leitura corrente em amperes elevador da ensacadeira 2' },
  'EN2_VAR_013': { name: 'Corrente % Exaustor Ens2', unit: '%', description: 'Leitura corrente em porcentagem exaustor filtro despoeiramento da ensacadeira' },
  'EN2_VAR_014': { name: 'Corrente Exaustor Ens2', unit: 'A', description: 'Leitura corrente em amperes exaustor filtro despoeiramento da ensacadeira' },
  'EN2_VAR_015': { name: 'Contador Sacos Anterior', unit: 'sacos', description: 'Contador de sacos Ensacadeira 2 (valor anterior)' },
  'EN2_VAR_016': { name: 'Contador Sacos Atual', unit: 'sacos', description: 'Contador de sacos Ensacadeira 2 (valor atual)' },
  'EN2_VAR_017': { name: 'Contador Sacos Geral', unit: 'sacos', description: 'Contador de sacos Ensacadeira 2 (valor geral)' },
  'EN2_VAR_018': { name: 'Horímetro Anterior H', unit: 'h', description: 'Horímetro anterior Ensacadeira 2 (Hora)' },
  'EN2_VAR_019': { name: 'Horímetro Anterior Min', unit: 'min', description: 'Horímetro anterior Ensacadeira 2 (Minuto)' },
  'EN2_VAR_020': { name: 'Horímetro Anterior Seg', unit: 's', description: 'Horímetro anterior Ensacadeira 2 (Segundo)' },
  'EN2_VAR_021': { name: 'Horímetro Atual H', unit: 'h', description: 'Horímetro atual Ensacadeira 2 (Hora)' },
  'EN2_VAR_022': { name: 'Horímetro Atual Min', unit: 'min', description: 'Horímetro atual Ensacadeira 2 (Minuto)' },
  'EN2_VAR_023': { name: 'Horímetro Atual Seg', unit: 's', description: 'Horímetro atual Ensacadeira 2 (Segundo)' },
  'EN2_VAR_024': { name: 'Horímetro Geral H', unit: 'h', description: 'Horímetro geral Ensacadeira 2 (Hora)' },
  'EN2_VAR_025': { name: 'Horímetro Geral Min', unit: 'min', description: 'Horímetro geral Ensacadeira 2 (Minuto)' },
  'EN2_VAR_026': { name: 'Horímetro Geral Seg', unit: 's', description: 'Horímetro geral Ensacadeira 2 (Segundo)' },
  'EN2_VAR_027': { name: 'Produto Produzido', unit: '', description: 'Produto produzido (1=CPIII 40 RS, 2=CPII E40, 3=Ensacado CPII E 32 RS)' },
  'EN2_VAR_028': { name: 'Silo Selecionado', unit: '', description: 'Seleção silo ensacadeira (1=Silo 1, 2=Silo 2, 3=Silo 3, 4=Silo 4)' },
  'EN2_VAR_029': { name: 'Contador Sacos GEP', unit: 'sacos', description: 'Contador de sacos ensacadeira 2 para o GEP' },

  // EXPEDIÇÃO 1 (EX1) - 17 variáveis
  'EX1_VAR_010': { name: 'Status Tromba 2', unit: '', description: 'Sinaliza acoplado tromba 2 - GEP (1=Acoplado, 2=Desacoplado)' },
  'EX1_VAR_011': { name: 'Corrente % Eclusa Silo1', unit: '%', description: 'Leitura corrente em porcentagem da eclusa filtro despoeiramento silo cimento 1' },
  'EX1_VAR_012': { name: 'Corrente Eclusa Silo1', unit: 'A', description: 'Leitura corrente em amperes da eclusa filtro despoeiramento silo cimento 1' },
  'EX1_VAR_013': { name: 'Corrente % Vent Silo1', unit: '%', description: 'Leitura corrente em porcentagem do ventilador filtro despoeiramento silo cimento 1' },
  'EX1_VAR_014': { name: 'Corrente Vent Silo1', unit: 'A', description: 'Leitura corrente em amperes do ventilador filtro despoeiramento silo cimento 1' },
  'EX1_VAR_015': { name: 'Corrente % Vent Silo2', unit: '%', description: 'Leitura corrente em porcentagem do ventilador filtro despoeiramento silo cimento 2' },
  'EX1_VAR_016': { name: 'Corrente Vent Silo2', unit: 'A', description: 'Leitura corrente em amperes do ventilador filtro despoeiramento silo cimento 2' },
  'EX1_VAR_017': { name: 'Corrente % Vent Silo3', unit: '%', description: 'Leitura corrente em porcentagem do ventilador filtro despoeiramento silo cimento 3' },
  'EX1_VAR_018': { name: 'Corrente Vent Silo3', unit: 'A', description: 'Leitura corrente em amperes do ventilador filtro despoeiramento silo cimento 3' },
  'EX1_VAR_019': { name: 'Corrente % Soprador Silo1', unit: '%', description: 'Leitura corrente em porcentagem soprador de fluidização do silo cimento 1' },
  'EX1_VAR_020': { name: 'Corrente Soprador Silo1', unit: 'A', description: 'Leitura corrente em amperes soprador de fluidização do silo cimento 1' },
  'EX1_VAR_021': { name: 'Corrente % Soprador Silo3', unit: '%', description: 'Leitura corrente em porcentagem soprador de fluidização do silo cimento 3' },
  'EX1_VAR_022': { name: 'Corrente Soprador Silo3', unit: 'A', description: 'Leitura corrente em amperes soprador de fluidização do silo cimento 3' },
  'EX1_VAR_023': { name: 'Corrente % Rosca Silo1', unit: '%', description: 'Leitura corrente em porcentagem rosca transportadora silo cimento 1' },
  'EX1_VAR_024': { name: 'Corrente Rosca Silo1', unit: 'A', description: 'Leitura corrente em amperes rosca transportadora silo cimento 1' },
  'EX1_VAR_025': { name: 'Corrente % Rosca Silo3', unit: '%', description: 'Leitura corrente em porcentagem rosca transportadora silo cimento 3' },
  'EX1_VAR_026': { name: 'Corrente Rosca Silo3', unit: 'A', description: 'Leitura corrente em amperes rosca transportadora silo cimento 3' },

  // EXPEDIÇÃO 2 (EX2) - 9 variáveis
  'EX2_VAR_010': { name: 'Status Tromba 2 Silo2', unit: '', description: 'Sinaliza acoplado tromba 2 - GEP (1=Acoplado, 2=Desacoplado)' },
  'EX2_VAR_011': { name: 'Corrente % Eclusa Silo2', unit: '%', description: 'Leitura corrente em porcentagem eclusa filtro despoeiramento tromba extração silo 2' },
  'EX2_VAR_012': { name: 'Corrente Eclusa Silo2', unit: 'A', description: 'Leitura corrente em amperes eclusa filtro despoeiramento tromba extração silo 2' },
  'EX2_VAR_013': { name: 'Corrente % Vent Tromba2', unit: '%', description: 'Leitura corrente em porcentagem ventilador filtro despoeiramento tromba extração silo 2' },
  'EX2_VAR_014': { name: 'Corrente Vent Tromba2', unit: 'A', description: 'Leitura corrente em amperes ventilador filtro despoeiramento tromba extração silo 2' },
  'EX2_VAR_015': { name: 'Corrente % Soprador Silo2', unit: '%', description: 'Leitura corrente em porcentagem soprador de fluidização do silo cimento 2' },
  'EX2_VAR_016': { name: 'Corrente Soprador Silo2', unit: 'A', description: 'Leitura corrente em amperes soprador de fluidização do silo cimento 2' },
  'EX2_VAR_017': { name: 'Corrente % Soprador Reserva', unit: '%', description: 'Leitura corrente em porcentagem soprador reserva fluidização dos silos cimento' },
  'EX2_VAR_018': { name: 'Corrente Soprador Reserva', unit: 'A', description: 'Leitura corrente em amperes soprador reserva fluidização dos silos cimento' },
};

export function getVariableInfo(key: string, sector: string) {
  if (VARIABLE_DESCRIPTIONS[key]) {
    return VARIABLE_DESCRIPTIONS[key];
  }

    const sectorName = sector.replace(/_/g, ' ');
  const match = key.match(/_VAR_(\d+)|_([A-Z_]+)$/);
  let varIdentifier = key;

  if (match) {
    if (match[1]) { // Formato _VAR_001
      varIdentifier = `Var ${parseInt(match[1], 10)}`;
    } else if (match[2]) { // Formato _TEN_L1_L2
      varIdentifier = match[2].replace(/_/g, ' ');
    }
  }
  
  return {
    name: `${sectorName} - ${varIdentifier}`,
    unit: 'N/D',
    description: `Variável de processo: ${key}`,
    isRunningIndicator: false
  };
}
