'use client'

import { useState, useEffect } from 'react'
import { Icon } from '@/components/ui/Icon'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import { ModalSection } from '@/components/ui/ModalSection'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'

interface FilterOption {
  id: string
  name: string
  code?: string
}

interface PendingAsset {
  id: string
  assetMaintenancePlanId: string
  assetName: string
  assetTag: string
  maintenanceName: string
  maintenanceTime: number
  timeUnit: string
  reason?: string
}

interface PlanFormPanelProps {
  onClose: () => void
  onSaved: (generatedCount?: number) => void
  inPage?: boolean
}

export function PlanFormPanel({ onClose, onSaved, inPage = false }: PlanFormPanelProps) {
  const [formData, setFormData] = useState({
    description: '',
    startDate: '',
    endDate: '',
    trackingType: 'TIME' as 'TIME' | 'HORIMETER',
    currentHorimeter: '' as string | number,
    toleranceDays: '' as string | number,
  })
  const [filters, setFilters] = useState({
    costCenterIds: [] as string[],
    workCenterIds: [] as string[],
    serviceTypeIds: [] as string[],
    maintenanceAreaIds: [] as string[],
  })
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [showConfirm, setShowConfirm] = useState(false)

  // Pending assets dialog (horímetro sem calendário)
  const [pendingAssets, setPendingAssets] = useState<PendingAsset[]>([])
  const [showPendingDialog, setShowPendingDialog] = useState(false)
  const [autoGeneratedCount, setAutoGeneratedCount] = useState(0)

  // Filter options loaded from APIs
  const [costCenters, setCostCenters] = useState<FilterOption[]>([])
  const [workCenters, setWorkCenters] = useState<FilterOption[]>([])
  const [serviceTypes, setServiceTypes] = useState<FilterOption[]>([])
  const [maintenanceAreas, setMaintenanceAreas] = useState<FilterOption[]>([])

  const todayStr = new Date().toLocaleDateString('pt-BR')

  useEffect(() => {
    Promise.all([
      fetch('/api/basic-registrations/cost-centers').then(r => r.json()),
      fetch('/api/basic-registrations/work-centers').then(r => r.json()),
      fetch('/api/basic-registrations/service-types').then(r => r.json()),
      fetch('/api/basic-registrations/maintenance-areas').then(r => r.json()),
    ]).then(([cc, wc, st, ma]) => {
      setCostCenters(cc.data || [])
      setWorkCenters(wc.data || [])
      setServiceTypes(st.data || [])
      setMaintenanceAreas(ma.data || [])
    }).catch(() => {})
  }, [])

  const toggleFilter = (key: keyof typeof filters, id: string) => {
    setFilters(prev => {
      const current = prev[key]
      const next = current.includes(id)
        ? current.filter(v => v !== id)
        : [...current, id]
      return { ...prev, [key]: next }
    })
  }

  const handleRequestOpen = (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    if (!formData.description || !formData.startDate || !formData.endDate) {
      setError('Preencha todos os campos obrigatórios.')
      return
    }
    if (formData.trackingType === 'HORIMETER' && (!formData.currentHorimeter || Number(formData.currentHorimeter) <= 0)) {
      setError('Informe o horímetro atual para planos por horímetro.')
      return
    }
    setShowConfirm(true)
  }

  const handleConfirm = async () => {
    setShowConfirm(false)
    setSaving(true)
    setError('')
    try {
      const res = await fetch('/api/planning/plans', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...formData,
          currentHorimeter: formData.currentHorimeter ? Number(formData.currentHorimeter) : undefined,
          toleranceDays: formData.toleranceDays ? Number(formData.toleranceDays) : 0,
          ...filters,
        }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error || 'Erro ao salvar')
        setSaving(false)
        return
      }

      // Check if there are pending assets that need user selection
      if (data.pendingAssets && data.pendingAssets.length > 0) {
        setAutoGeneratedCount(data.generatedCount || 0)
        setPendingAssets(data.pendingAssets)
        setShowPendingDialog(true)
        setSaving(false)
        return
      }

      onSaved(data.generatedCount)
    } catch {
      setError('Erro de conexão')
    }
    setSaving(false)
  }

  const handleSkipPending = () => {
    setShowPendingDialog(false)
    onSaved(autoGeneratedCount)
  }

  const renderMultiSelect = (
    label: string,
    options: FilterOption[],
    selected: string[],
    filterKey: keyof typeof filters,
  ) => (
    <div>
      <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
        {label}
      </label>
      {options.length === 0 ? (
        <p className="text-xs text-muted-foreground italic">Nenhum cadastrado</p>
      ) : (
        <div className="border border-input rounded-[4px] max-h-36 overflow-y-auto">
          {options.map(opt => {
            const isSelected = selected.includes(opt.id)
            return (
              <label
                key={opt.id}
                className={`flex items-center gap-2 px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 transition-colors ${isSelected ? 'bg-accent-orange/10' : ''}`}
              >
                <input
                  type="checkbox"
                  checked={isSelected}
                  onChange={() => toggleFilter(filterKey, opt.id)}
                  className="rounded border-gray-300 text-accent-orange focus:ring-accent-orange"
                />
                <span className="truncate">
                  {opt.code ? `${opt.code} - ${opt.name}` : opt.name}
                </span>
              </label>
            )
          })}
        </div>
      )}
      {selected.length > 0 && (
        <p className="text-[11px] text-muted-foreground mt-0.5">
          {selected.length} selecionado{selected.length > 1 ? 's' : ''}
        </p>
      )}
    </div>
  )

  const formContent = (
    <>
      {error && (
        <div className="p-3 bg-danger/10 text-danger rounded-[4px] text-sm">{error}</div>
      )}

      <ModalSection title="Identificação do Plano">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              N° do Plano
            </label>
            <input
              type="text"
              value="(Automático)"
              disabled
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] bg-gray-100 text-muted-foreground cursor-not-allowed"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Data do Plano
            </label>
            <input
              type="text"
              value={todayStr}
              disabled
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] bg-gray-100 text-muted-foreground cursor-not-allowed"
            />
          </div>
          <div className="sm:col-span-2">
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Descrição <span className="text-danger">*</span>
            </label>
            <input
              type="text"
              value={formData.description}
              onChange={e => setFormData({ ...formData, description: e.target.value })}
              placeholder="Ex: Plano Lubrificação Abril 2026"
              required
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
        </div>
      </ModalSection>

      <ModalSection title="Tipo de Controle e Período">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Tipo de Controle <span className="text-danger">*</span>
            </label>
            <select
              value={formData.trackingType}
              onChange={e => setFormData({ ...formData, trackingType: e.target.value as 'TIME' | 'HORIMETER' })}
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] bg-background focus:outline-none focus:ring-2 focus:ring-ring"
            >
              <option value="TIME">Tempo Pré-determinado</option>
              <option value="HORIMETER">Horímetro</option>
            </select>
          </div>
          {formData.trackingType === 'HORIMETER' && (
            <div>
              <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                Horímetro Atual <span className="text-danger">*</span>
              </label>
              <input
                type="number"
                min="0"
                step="0.01"
                value={formData.currentHorimeter}
                onChange={e => setFormData({ ...formData, currentHorimeter: e.target.value })}
                placeholder="Ex: 5000"
                className="w-full px-3 py-2 text-sm border border-input rounded-[4px] focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
          )}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Data Início <span className="text-danger">*</span>
            </label>
            <input
              type="date"
              value={formData.startDate}
              onChange={e => setFormData({ ...formData, startDate: e.target.value })}
              required
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Data Fim <span className="text-danger">*</span>
            </label>
            <input
              type="date"
              value={formData.endDate}
              onChange={e => setFormData({ ...formData, endDate: e.target.value })}
              required
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
              Tolerancia (dias)
            </label>
            <input
              type="number"
              min="0"
              value={formData.toleranceDays}
              onChange={e => setFormData({ ...formData, toleranceDays: e.target.value })}
              placeholder="Ex: 2"
              className="w-full px-3 py-2 text-sm border border-input rounded-[4px] focus:outline-none focus:ring-2 focus:ring-ring"
            />
            <p className="text-[11px] text-muted-foreground mt-0.5">
              Dias extras alem da data prevista antes de considerar a OS vencida
            </p>
          </div>
        </div>
      </ModalSection>

      <ModalSection title="Filtros">
        <p className="text-xs text-muted-foreground mb-3">
          Selecione os filtros para definir quais ativos terão OSs geradas neste plano.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {renderMultiSelect('Centro de Custo', costCenters, filters.costCenterIds, 'costCenterIds')}
          {renderMultiSelect('Centro de Trabalho', workCenters, filters.workCenterIds, 'workCenterIds')}
          {renderMultiSelect('Tipo de Serviço', serviceTypes, filters.serviceTypeIds, 'serviceTypeIds')}
          {renderMultiSelect('Área de Manutenção', maintenanceAreas, filters.maintenanceAreaIds, 'maintenanceAreaIds')}
        </div>
      </ModalSection>

      <div className="p-3 bg-muted rounded-[4px] text-xs text-muted-foreground">
        {formData.trackingType === 'TIME'
          ? 'Ao abrir o plano, o sistema emitirá automaticamente Ordens de Serviço para os ativos com manutenção prevista por tempo dentro do período e filtros selecionados.'
          : 'Ao abrir o plano, o sistema emitirá OSs para os ativos com manutenção prevista por horímetro, usando o calendário vinculado ao Plano do Bem para projetar as datas. Ativos sem calendário vinculado não terão OSs geradas.'}
      </div>
    </>
  )

  const formFooter = (
    <div className="flex gap-3 px-4 py-4 border-t border-border">
      <Button type="button" variant="outline" onClick={onClose} className="flex-1">
        Cancelar
      </Button>
      <Button type="submit" disabled={saving} className="flex-1 bg-accent-orange hover:bg-accent-orange/90 text-white font-bold">
        <Icon name="assignment" className="text-base mr-2" />
        {saving ? 'Processando...' : 'Abrir Plano'}
      </Button>
    </div>
  )

  const confirmDialog = (
    <ConfirmDialog
      isOpen={showConfirm}
      onClose={() => setShowConfirm(false)}
      onConfirm={handleConfirm}
      title="Emitir Ordens de Serviço"
      message="Deseja emitir as Ordens de Serviço para o plano selecionado?"
      confirmText="Sim"
      cancelText="Não"
      variant="info"
      loading={saving}
    />
  )

  const pendingAssetsDialog = showPendingDialog && (
    <Modal
      isOpen
      onClose={handleSkipPending}
      title="Ativos sem Calendario"
      size="lg"
    >
      <div className="p-4 space-y-3">
        <div className="p-3 bg-warning/10 border border-warning/30 rounded-[4px] text-sm text-warning-foreground">
          <p className="font-semibold mb-1">Atenção</p>
          <p className="text-xs">
            Os ativos abaixo possuem manutenção por horímetro cadastrada, mas não têm calendário vinculado
            no Plano do Bem. O calendário é obrigatório para calcular as datas das OSs por horímetro.
            Para gerar OSs para esses ativos, vincule um calendário no cadastro de Manutenção do Bem.
          </p>
        </div>

        {autoGeneratedCount > 0 && (
          <p className="text-sm text-muted-foreground">
            {autoGeneratedCount} OS(s) foram geradas automaticamente para ativos com calendário vinculado.
          </p>
        )}

        <div className="border border-input rounded-[4px] max-h-64 overflow-y-auto">
          {pendingAssets.map(pa => (
            <div
              key={pa.assetMaintenancePlanId}
              className="flex items-start gap-3 px-4 py-3 border-b border-gray-100 last:border-b-0"
            >
              <Icon name="warning" className="text-base text-warning mt-0.5 shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-foreground truncate">
                  {pa.assetName} <span className="text-muted-foreground">({pa.assetTag})</span>
                </p>
                <p className="text-xs text-muted-foreground">
                  {pa.maintenanceName} — Frequência: {pa.maintenanceTime} {pa.timeUnit}
                </p>
                {pa.reason && (
                  <p className="text-xs text-danger mt-0.5">{pa.reason}</p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="flex gap-3 px-4 py-4 border-t border-border">
        <Button type="button" onClick={handleSkipPending} className="flex-1">
          Entendido
        </Button>
      </div>
    </Modal>
  )

  if (inPage) {
    return (
      <div className="h-full flex flex-col bg-card border-l border-border">
        <div className="flex items-center justify-between p-4 border-b border-border">
          <h2 className="text-xl font-bold text-foreground">Novo Plano de Manutenção</h2>
          <button onClick={onClose} className="p-1 hover:bg-muted rounded transition-colors">
            <Icon name="close" className="text-xl text-muted-foreground" />
          </button>
        </div>
        <form onSubmit={handleRequestOpen} className="flex flex-1 min-h-0 flex-col">
          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {formContent}
          </div>
          {formFooter}
        </form>
        {confirmDialog}
        {pendingAssetsDialog}
      </div>
    )
  }

  return (
    <Modal isOpen onClose={onClose} title="Novo Plano de Manutenção" size="wide">
      <form onSubmit={handleRequestOpen}>
        <div className="p-4 space-y-3">
          {formContent}
        </div>
        {formFooter}
      </form>
      {confirmDialog}
      {pendingAssetsDialog}
    </Modal>
  )
}
